name: CI

on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout repository
     uses: actions/checkout@v2

   - name: Set up JDK
     uses: actions/setup-java@v2
     with:
      java-version: '11'
      distribution: 'adopt'

   - name: Build and Test
     run: |
      ./gradlew build --info
      ./gradlew test

